# Generated by Django 4.0.2 on 2022-02-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='url',
            name='url_short_u_0b2618_idx',
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['short_url'], name='urlshortene_short_u_5b9918_idx'),
        ),
        migrations.AlterModelTable(
            name='url',
            table=None,
        ),
    ]
