# Generated by Django 4.0.2 on 2022-02-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_remove_url_url_short_u_0b2618_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='url',
            name='urlshortene_short_u_5b9918_idx',
        ),
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['short_url'], name='url_short_u_0b2618_idx'),
        ),
        migrations.AlterModelTable(
            name='url',
            table='url',
        ),
    ]
