# Generated by Django 4.0.2 on 2022-02-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_remove_url_urlshortene_short_u_5b9918_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.TextField(max_length=10),
        ),
    ]
